-- Initial regional bank for Diego Domanico's review. Nothing in this file is
-- playable until status is changed from review to approved with approval metadata.

insert into public.questions (
  competency_id, difficulty, applicable_countries, prompt, options, correct_index,
  explanation, source_url, source_title, source_checked_at, status
) values
(1, 1, '{}',
 '¿Qué acción ayuda más a que un comprador encuentre el producto correcto mediante búsquedas y filtros?',
 '["Repetir palabras en el título", "Elegir la categoría correcta y completar los atributos", "Agregar información de envío al título", "Crear varias publicaciones idénticas"]', 1,
 'La categoría y los atributos precisos permiten clasificar el producto y hacerlo visible en los filtros relevantes.',
 'https://vendedores.mercadolibre.cl/nota/como-crear-publicaciones-efectivas-en-mercado-libre',
 'Cómo crear publicaciones y alcanzar más compradores', '2026-07-10', 'review'),
(1, 2, '{}',
 'Una publicación tiene objetivos de calidad pendientes. ¿Qué dos grupos conviene revisar primero?',
 '["Seguidores y mensajes", "Logo y nombre de la tienda", "Datos del producto y condiciones de venta", "Antigüedad de la cuenta y cantidad de empleados"]', 2,
 'Mercado Libre organiza las oportunidades de calidad entre datos del producto y condiciones de venta; ambas afectan competitividad.',
 'https://vendedores.mercadolibre.cl/nota/como-lograr-una-publicacion-mas-competitiva',
 'Cómo lograr una publicación más competitiva', '2026-07-10', 'review'),
(1, 3, '{}',
 'Tu producto compite en catálogo, pero otro vendedor queda destacado. ¿Cuál es la intervención más sólida?',
 '["Duplicar la publicación muchas veces", "Mejorar condiciones de venta y experiencia sin alterar la identidad del producto", "Cambiar el modelo declarado", "Agregar palabras promocionales al título"]', 1,
 'En catálogo, la oferta destacada depende de la combinación de condiciones y experiencia. La identidad del producto debe seguir siendo exacta.',
 'https://vendedores.mercadolibre.cl/nota/que-significa-que-tu-publicacion-sea-elegible-para-catalogo',
 'Qué significa que tu publicación sea elegible para competir', '2026-07-10', 'review'),
(1, 4, '{}',
 'Una portada recibe visitas pero genera dudas sobre qué incluye el producto. ¿Qué corrección priorizarías?',
 '["Agregar un banner con el precio", "Mostrar productos accesorios que no se entregan", "Aplicar una marca de agua grande", "Mostrar con claridad sólo lo ofrecido y trasladar el contexto a fotos complementarias"]', 3,
 'La portada debe representar con fidelidad lo que se entrega. El contexto y los detalles pueden mostrarse después sin confundir el alcance de la oferta.',
 'https://vendedores.mercadolibre.cl/nota/las-fotos-son-la-cara-de-tu-negocio-lucite-en-ellas',
 'Las fotos son la cara de tu negocio', '2026-07-10', 'review'),
(1, 5, '{}',
 'Una publicación profesional recibe muchas visitas y pocas ventas. ¿Cuál es el mejor diagnóstico inicial?',
 '["Cambiar la categoría sin evidencia", "Subir el precio para transmitir calidad", "Comparar precio, financiación, entrega y confianza frente a ofertas equivalentes", "Eliminar atributos para simplificar"]', 2,
 'Muchas visitas con baja conversión indican que la demanda existe, pero la propuesta pierde al momento de elegir. Hay que revisar condiciones y confianza comparables.',
 'https://vendedores.mercadolibre.com.ar/nota/analisis-de-la-competencia-como-hacerlo-y-para-que-sirve',
 'Análisis de la competencia', '2026-07-10', 'review'),

(2, 1, '{}',
 '¿Qué solución de Mercado Ads permite promocionar publicaciones de productos dentro del marketplace?',
 '["Product Ads", "Mercado Enlace", "Seller Boost", "Catálogo Plus"]', 0,
 'Product Ads promociona publicaciones y participa en espacios publicitarios dentro de Mercado Libre.',
 'https://vendedores.mercadolibre.com.ar/nota/como-se-priorizan-tus-anuncios-en-product-ads',
 'Cómo se priorizan tus anuncios en Product Ads', '2026-07-10', 'review'),
(2, 2, '{}',
 'Si una campaña informa un ROAS de 8, ¿cómo se interpreta correctamente?',
 '["Se invirtieron 8 unidades por cada venta", "Se generaron 8 unidades de ingresos atribuibles por cada unidad invertida", "El margen neto fue 8%", "Ocho de cada diez clics compraron"]', 1,
 'ROAS relaciona ingresos atribuidos con inversión publicitaria. No equivale a margen ni a tasa de conversión.',
 'https://vendedores.mercadolibre.com.ar/nota/como-se-priorizan-tus-anuncios-en-product-ads',
 'Cómo se priorizan tus anuncios en Product Ads', '2026-07-10', 'review'),
(2, 3, '{}',
 'Una campaña obtiene muchas impresiones y muy pocos clics. ¿Qué hipótesis debe evaluarse primero?',
 '["La postventa es demasiado rápida", "Hay exceso de stock", "La oferta parece poco relevante por foto, título, precio o condiciones", "El costo logístico se registró dos veces"]', 2,
 'La brecha entre impresiones y clics apunta primero a relevancia y atractivo de la oferta mostrada, antes que a problemas posteriores a la visita.',
 'https://vendedores.mercadolibre.com.ar/nota/como-se-priorizan-tus-anuncios-en-product-ads',
 'Cómo se priorizan tus anuncios en Product Ads', '2026-07-10', 'review'),
(2, 4, '{}',
 'Los anuncios generan clics, pero la conversión cae al mismo tiempo que aumentan preguntas sobre el producto. ¿Qué harías antes de elevar la inversión?',
 '["Aumentar el presupuesto sin cambios", "Pausar toda la cuenta", "Reducir el stock publicado", "Corregir información, imágenes y condiciones que están frenando la decisión"]', 3,
 'Más tráfico no corrige una publicación que no resuelve dudas. Primero se elimina la fricción de conversión y luego se escala la inversión.',
 'https://vendedores.mercadolibre.cl/nota/como-crear-publicaciones-de-calidad',
 'Cómo garantizar la calidad de tus publicaciones', '2026-07-10', 'review'),
(2, 5, '{}',
 'Una línea tiene margen ajustado y una meta agresiva de crecimiento. ¿Cómo definirías el objetivo publicitario?',
 '["Copiando el ACOS de cualquier competidor", "Buscando siempre el máximo alcance", "Calculando el ACOS máximo sostenible y el ROAS compatible con margen y objetivo", "Usando el mismo objetivo para todo el catálogo"]', 2,
 'El objetivo debe conectar inversión, ingreso y margen. Un producto de margen estrecho tolera un costo publicitario distinto que uno de alto margen.',
 'https://vendedores.mercadolibre.com.ar/nota/como-se-priorizan-tus-anuncios-en-product-ads',
 'Cómo se priorizan tus anuncios en Product Ads', '2026-07-10', 'review'),

(3, 1, '{}',
 '¿Qué práctica evita mejor cancelaciones causadas por productos que ya no están disponibles?',
 '["Mantener el stock publicado sincronizado con el inventario real", "Esperar a que el comprador pregunte", "Cancelar después de vender", "Ocultar las variantes"]', 0,
 'El stock publicado debe representar disponibilidad real por producto y variante para no prometer unidades inexistentes.',
 'https://vendedores.mercadolibre.cl/nota/como-crear-publicaciones-de-calidad',
 'Cómo garantizar la calidad de tus publicaciones', '2026-07-10', 'review'),
(3, 2, '{AR,CL}',
 '¿Cuál describe mejor la diferencia operativa entre Full y Flex?',
 '["Ambos requieren almacenar todo en Mercado Libre", "Full almacena y despacha desde centros de Mercado Libre; Flex usa logística del vendedor para entregas rápidas", "Flex sólo sirve para productos usados", "Full no administra inventario"]', 1,
 'Full delega almacenamiento y preparación; Flex permite entregas rápidas con la operación logística del vendedor. La disponibilidad exacta depende de cada país y cuenta.',
 'https://vendedores.mercadolibre.com.ar/aprender/nota/utiliza-envios-flex-y-full-en-una-misma-publicacion',
 'Cómo usar Envíos Flex y Full en una misma publicación', '2026-07-10', 'review'),
(3, 3, '{}',
 'Las cancelaciones por falta de stock crecen aunque el depósito tiene inventario. ¿Qué control revisarías primero?',
 '["El color del logo", "La cantidad de seguidores", "El texto de bienvenida", "La sincronización por SKU y variante entre todos los canales"]', 3,
 'Cuando hay inventario físico pero se cancela, suele fallar la disponibilidad por SKU, variante o canal. El control debe reconciliar esas fuentes.',
 'https://vendedores.mercadolibre.cl/nota/como-publicar-en-mercado-libre-por-primera-vez',
 'Cómo publicar en Mercado Libre por primera vez', '2026-07-10', 'review'),
(3, 4, '{AR,CL}',
 'Una publicación opera con Full y Flex. ¿Qué principio permite administrar ambas modalidades correctamente?',
 '["Mantener stocks separados y dejar que se priorice la mejor promesa de entrega y costo", "Duplicar manualmente cada venta", "Asignar todo el stock a Flex", "Ocultar Full cuando existe stock propio"]', 0,
 'Las modalidades administran disponibilidades separadas y pueden convivir para ofrecer la mejor promesa posible sin mezclar inventarios.',
 'https://vendedores.mercadolibre.com.ar/aprender/nota/utiliza-envios-flex-y-full-en-una-misma-publicacion',
 'Cómo usar Envíos Flex y Full en una misma publicación', '2026-07-10', 'review'),
(3, 5, '{}',
 'Se acerca una campaña de alta demanda y el proveedor tarda 20 días en reponer. ¿Qué decisión es más robusta?',
 '["Esperar a quedarse sin stock", "Comprar sólo según ventas de ayer", "Proyectar demanda, plazo de reposición, variabilidad y stock de seguridad por SKU", "Publicar inventario que todavía no fue confirmado"]', 2,
 'La cobertura debe considerar velocidad esperada, lead time y variabilidad. El stock de seguridad protege la promesa sin inflar disponibilidad ficticia.',
 'https://vendedores.mercadolibre.com.ar/nota/analisis-de-la-competencia-como-hacerlo-y-para-que-sirve',
 'Análisis de la competencia', '2026-07-10', 'review'),

(4, 1, '{}',
 '¿Qué respuesta ayuda más a convertir una pregunta de un comprador?',
 '["Una respuesta genérica varias horas después", "Pedirle que busque la información", "Responder rápido, con claridad y resolviendo exactamente la duda", "Enviar información de otro producto"]', 2,
 'La velocidad importa, pero la respuesta también debe ser clara, pertinente y suficiente para reducir incertidumbre.',
 'https://vendedores.mercadolibre.cl/aprender/nota/como-publicar-correctamente-tu-servicio',
 'Cómo publicar correctamente tu servicio', '2026-07-10', 'review'),
(4, 2, '{}',
 '¿Qué combinación reduce preguntas evitables y reclamos por expectativas incorrectas?',
 '["Título promocional y pocas fotos", "Título, atributos, variantes, imágenes y descripción consistentes", "Ocultar limitaciones del producto", "Responder sólo después de la venta"]', 1,
 'La consistencia entre todos los elementos de la publicación ayuda al comprador a entender qué recibirá y evita diferencias de expectativa.',
 'https://vendedores.mercadolibre.cl/nota/como-crear-publicaciones-de-calidad',
 'Cómo garantizar la calidad de tus publicaciones', '2026-07-10', 'review'),
(4, 3, '{}',
 'Aumentan los reclamos porque el producto recibido no coincide con la variante elegida. ¿Cuál es la corrección de raíz?',
 '["Ofrecer un cupón sin investigar", "Eliminar todas las variantes", "Cambiar el nombre de la tienda", "Auditar SKU, atributos, fotos, picking y etiquetado de cada variante"]', 3,
 'El problema cruza publicación y preparación. Corregir sólo la comunicación o sólo el depósito dejaría abierta parte de la causa.',
 'https://vendedores.mercadolibre.com.mx/nota/como-mejorar-la-reputacion',
 'Cómo mejorar la reputación', '2026-07-10', 'review'),
(4, 4, '{AR,CL}',
 'Un equipo memoriza un porcentaje de reputación tomado de otro país. ¿Qué debería hacer antes de tomar decisiones?',
 '["Aplicarlo igual en toda Latinoamérica", "Consultar la métrica vigente de su cuenta y la documentación del país", "Ignorar la reputación", "Cambiar de categoría"]', 1,
 'Los criterios, períodos y herramientas pueden variar por país y evolucionar. La fuente vigente de la cuenta local tiene prioridad sobre reglas memorizadas.',
 'https://vendedores.mercadolibre.com.mx/nota/por-que-es-importante-la-reputacion-del-vendedor',
 'Por qué es importante la reputación del vendedor', '2026-07-10', 'review'),
(4, 5, '{}',
 'Un reclamo individual revela un patrón que también aparece en reseñas y devoluciones. ¿Cuál es la mejor respuesta gerencial?',
 '["Resolver sólo ese caso", "Discutir públicamente con el comprador", "Resolver al comprador, contener el riesgo y corregir la causa en publicación y operación", "Pausar todos los productos sin analizar"]', 2,
 'La excelencia combina recuperación del caso y aprendizaje sistémico. El patrón debe traducirse en una corrección verificable del proceso.',
 'https://vendedores.mercadolibre.com.mx/nota/como-mejorar-la-reputacion',
 'Cómo mejorar la reputación', '2026-07-10', 'review'),

(5, 1, '{}',
 '¿Qué significa gestionar un negocio de manera data driven?',
 '["Medir resultados, formular hipótesis y decidir con evidencia", "Copiar siempre al competidor", "Evitar toda intuición", "Mirar sólo la facturación"]', 0,
 'Decidir con datos implica medir, interpretar y experimentar. La facturación aislada no explica rentabilidad, conversión ni calidad operativa.',
 'https://vendedores.mercadolibre.com.ar/nota/analisis-de-la-competencia-como-hacerlo-y-para-que-sirve',
 'Análisis de la competencia', '2026-07-10', 'review'),
(5, 2, '{}',
 '¿Cómo se obtiene conceptualmente el margen de contribución de una venta?',
 '["Precio menos impuestos solamente", "Ventas divididas por visitas", "Precio multiplicado por reputación", "Ingreso neto menos producto, cargos, envío, publicidad y otros costos variables"]', 3,
 'El margen de contribución descuenta los costos que cambian con la venta. Sirve para saber cuánto queda para cubrir estructura y generar resultado.',
 'https://vendedores.mercadolibre.com.ar/nota/como-se-priorizan-tus-anuncios-en-product-ads',
 'Cómo se priorizan tus anuncios en Product Ads', '2026-07-10', 'review'),
(5, 3, '{}',
 'Las ventas suben 30%, pero el resultado económico baja. ¿Qué análisis debe hacerse primero?',
 '["Contar seguidores", "Recalcular contribución por SKU incluyendo publicidad, cargos, descuentos y logística", "Aumentar todo el presupuesto", "Eliminar el producto más vendido"]', 1,
 'Más volumen puede destruir valor cuando el costo incremental supera el margen. El análisis debe hacerse por SKU y condición comercial.',
 'https://vendedores.mercadolibre.com.ar/nota/como-se-priorizan-tus-anuncios-en-product-ads',
 'Cómo se priorizan tus anuncios en Product Ads', '2026-07-10', 'review'),
(5, 4, '{}',
 'Tu conversión está debajo de vendedores líderes de la categoría. ¿Cómo usarías la comparación?',
 '["Compararía condiciones y calidad, cuantificaría brechas y priorizaría la de mayor impacto", "Copiaría todos sus precios sin calcular margen", "Cambiaría todos los títulos", "Ignoraría las diferencias de operación"]', 0,
 'El benchmark sirve para detectar brechas, no para copiar sin contexto. La prioridad depende del impacto esperado y la economía del propio negocio.',
 'https://vendedores.mercadolibre.com.ar/nota/analisis-de-la-competencia-como-hacerlo-y-para-que-sirve',
 'Análisis de la competencia', '2026-07-10', 'review'),
(5, 5, '{}',
 'Tenés presupuesto limitado para stock y publicidad en varios SKU. ¿Qué criterio produce una asignación más sólida?',
 '["Repartir igual entre todos", "Invertir sólo en el producto más caro", "Elegir el SKU con más visitas sin mirar margen", "Priorizar contribución incremental esperada considerando demanda, margen, stock y capacidad operativa"]', 3,
 'La mejor asignación maximiza valor incremental dentro de restricciones reales. Una sola métrica puede llevar a financiar volumen no rentable o imposible de cumplir.',
 'https://vendedores.mercadolibre.com.ar/nota/analisis-de-la-competencia-como-hacerlo-y-para-que-sirve',
 'Análisis de la competencia', '2026-07-10', 'review');
